name: Build Electron App

on:
  push:
    paths:
      - 'desktop-app/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: desktop-app

      - name: Build Electron Windows App
        run: npm run dist
        working-directory: desktop-app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Setup-PC-Monitor-App
          path: desktop-app/dist/*.exe
